
[world]

	[world.biomes]

		[world.biomes.dunes]
			"Rocky Dunes weight" = 2
			"Rocky Dunes Hills weight" = 1
			"Dunes Hills weight" = 1
			"Flourishing Dunes weight" = 1
			"Petrified Dunes weight" = 1
			"Dunes weight" = 3

		[world.biomes.rainforest]
			"Rainforest weight" = 1
			"Rainforest Plateau weight" = 1
			"Rainforest Basin weight" = 1
			"Sparse Rainforest Basin weight" = 1
			"Rainforest Mountains weight" = 1
			"Sparse Rainforest Plateau weight" = 1

		#These biomes are experimental and not ready for use in gameplay
		[world.biomes.experimental]

			[world.biomes.experimental.hot_springs]
				"Hot Springs weight" = 0

